import fs from "fs";
import https from "https";
import { URL } from "url";
if (fs.existsSync(".env")) { for (const line of fs.readFileSync(".env","utf8").split(/\r?\n/)) { const t=line.trim(); if(!t||t.startsWith("#"))continue; const i=line.indexOf("="); if(i<0)continue; const k=line.slice(0,i).trim(); let v=line.slice(i+1).trim(); if((v.startsWith("\"")&&v.endsWith("\""))||(v.startsWith("'")&&v.endsWith("'")))v=v.slice(1,-1); if(process.env[k]===undefined)process.env[k]=v; } }
const BASE = (process.env.WARRANTY_BASE_URL||"http://103.160.12.43").replace("https://103.160.12.43","http://103.160.12.43");
function fetchH(urlStr,opt={}){return new Promise((res,rej)=>{const u=new URL(urlStr);const c=u.protocol==="https:"?https:null;const req=c.request({hostname:u.hostname,port:u.port||443,path:u.pathname+u.search,method:opt.method||"GET",headers:opt.headers||{},rejectUnauthorized:false},r=>{let ch=[];r.on("data",x=>ch.push(x));r.on("end",()=>res({status:r.statusCode,setCookie:r.headers["set-cookie"]||[],text:async()=>Buffer.concat(ch).toString("utf8")}));});req.on("error",rej);req.end();});}
async function login(){const U=process.env.CRO_USER,P=process.env.CRO_PASS,T=process.env.CRO_TOKEN,D=process.env.WARRANTY_KODE_DEALER,DPT=process.env.WARRANTY_DEPT;const bh={"User-Agent":"Mozilla/5.0","Accept":"text/html,*/*"};const lp=await fetchH(`${BASE}/aftersales/login`,{headers:bh});const lh=await lp.text();let jar={};for(const c of lp.setCookie){const[p]=c.split(";");const i=p.indexOf("=");if(i>0)jar[p.slice(0,i).trim()]=p.slice(i+1).trim();}const csrf=(lh.match(/name="_token"\s+value="([^"]+)"/)||[])[1]||"";const cs=()=>Object.entries(jar).map(([k,v])=>`${k}=${v}`).join("; ");const lb=new URLSearchParams({_token:csrf,username:U,password:P}).toString();const lr=await fetchH(`${BASE}/aftersales/login`,{method:"POST",headers:{...bh,"Content-Type":"application/x-www-form-urlencoded","Content-Length":Buffer.byteLength(lb),"Cookie":cs()},body:lb});for(const c of lr.setCookie){const[p]=c.split(";");const i=p.indexOf("=");if(i>0)jar[p.slice(0,i).trim()]=p.slice(i+1).trim();}const tp=await fetchH(`${BASE}/aftersales/token`,{headers:{...bh,"Cookie":cs()}});if(tp.status===302)return cs();const th=await tp.text();const tc=(th.match(/name="_token"\s+value="([^"]+)"/)||[])[1]||csrf;const tb=new URLSearchParams({_token:tc,kode_dealer:D,token:T,dept_hidden:DPT}).toString();await fetchH(`${BASE}/aftersales/token`,{method:"POST",headers:{...bh,"Content-Type":"application/x-www-form-urlencoded","Content-Length":Buffer.byteLength(tb),"Cookie":cs()},body:tb});return cs();}
const cookie=await login();
for (const [off,len] of [[0,100],[0,10],[10,10]]) {
  const url=`${BASE}/aftersales/reminder-do/data?draw=1&start=${off}&length=${len}&do_from=07-07-2026&do_to=06-08-2026&status_filter=all&grup=&_=${Date.now()}`;
  const r=await fetchH(url,{headers:{"Cookie":cookie,"User-Agent":"Mozilla/5.0","Referer":`${BASE}/aftersales/reminder-do`,"Accept":"application/json, text/javascript, */*; q=0.01","X-Requested-With":"XMLHttpRequest"}});
  const t=await r.text();const j=JSON.parse(t);console.log(`start=${off} len=${len} => status=${r.status} recordsTotal=${j.recordsTotal} recordsFiltered=${j.recordsFiltered} returned=${j.data?.length}`);
}
